apiVersion: v1
kind: Service
metadata:
  name: to-do-list-service
spec:
  selector:
    app: to-do-list
  ports:
    - port: 4000
      name: frontend
      targetPort: 4000
    - port: 4001
      name: backend
      targetPort: 4001
  type: LoadBalancer
